name: dart_flutter_team_lints
description: An analysis rule set used by the Dart and Flutter teams.
version: 3.6.0-wip
repository: https://github.com/dart-lang/ecosystem/tree/main/pkgs/dart_flutter_team_lints
issue_tracker: https://github.com/dart-lang/ecosystem/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Adart_flutter_team_lints

environment:
  sdk: ^3.10.0

dependencies:
  lints: ^6.0.0

dev_dependencies:
  checks: ^0.3.0
  path: ^1.8.0
  test: ^1.24.0
  yaml: ^3.0.0
