name: corpus
description: A tool to calculate the API usage for a package.

publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^8.0.0
  args: ^2.1.0
  cli_util: ^0.4.0
  collection: ^1.19.0
  http: ^1.0.0
  path: ^1.9.0
  pub_semver: ^2.1.4
  yaml: ^3.0.0

dev_dependencies:
  checks: ^0.3.0
  dart_flutter_team_lints: ^3.0.0
  test: ^1.25.9
  test_descriptor: ^2.0.0
