name: package4
description: A starting point for Dart libraries or applications.
version: 1.2.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  path: any
  intl: any

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  http_io: any
