name: firehose
description: A tool to automate publishing of Pub packages from GitHub actions.
version: 0.3.14
repository: https://github.com/dart-lang/ecosystem/tree/main/pkgs/firehose

# todo: temporary change to trigger a publish warning
authors:
  - devoncarew@google.con

# todo: test no labels
# todo: test multiple labels

environment:
  sdk: '>=2.19.0 <3.0.0'

executables:
  firehose: firehose

dependencies:
  args: ^2.3.0
  collection: ^1.17.0
  http: ^0.13.0
  path: ^1.8.0
  pub_semver: ^2.1.0
  yaml: ^3.1.0

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  test: ^1.21.0
