name: repo_query
description: Miscellaneous issue, repo, and PR query tools.

publish_to: none

environment:
  sdk: ^2.19.0

dependencies:
  args: any
  graphql: any
  http: any
  path: any

dev_dependencies:
  dart_flutter_team_lints: any
