name: blast_repo
description: A tool to bulk validate and fix GitHub repos.

publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.3.1
  collection: ^1.17.0
  firehose:
    path:  ../firehose
  git: ^2.2.0
  github: ^9.6.0
  io: ^1.0.0
  meta: ^1.8.0
  path: ^1.8.2
  pub_semver: ^2.1.2
  stack_trace: ^1.11.0
  yaml: ^3.1.0
  yaml_edit: ^2.1.0

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  test: ^1.22.0
  test_descriptor: ^2.0.0

executables:
  blast_repo:
